# Generated by Django 2.2.8 on 2022-09-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionModelForm',
            fields=[
                ('type', models.CharField(choices=[('new', 'new'), ('contribute', 'contribute')], max_length=50)),
                ('id', models.FloatField(blank=True, default=0, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default=' ', max_length=500)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('biggest_for_now', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('closed', 'closed')], default='pending', max_length=50)),
            ],
        ),
    ]
