# Generated by Django 2.2.8 on 2022-09-05 05:04

from django.db import migrations
import django_ethereum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionmodelform',
            name='beneficiary',
            field=django_ethereum.fields.EthereumAddressField(blank=True, default='0x0000000000000000000000000000000000000000'),
        ),
        migrations.AddField(
            model_name='auctionmodelform',
            name='highest_bidder',
            field=django_ethereum.fields.EthereumAddressField(blank=True, default='0x0000000000000000000000000000000000000000'),
        ),
    ]
